tomlin7/biscuit

README.md
=> Include Usage instructions on README

src/lib/components/terminal/terminal.py, src/lib/components/utils/__init__.py, src/lib/components/utils/text_with_readonly.py
please check out if it works on windows :)
=> fix scrollbar and make text readonly

requirements.txt
Fixes #50. Now anyone using Biscuit can use it without any hassle!
=> Fixes requirements.txt.

biscuit/core/components/floating/notifications/__init__.py, biscuit/core/components/games/pong.py, biscuit/core/components/games/snake.py, biscuit/core/components/views/panel/terminal/__init__.py, biscuit/core/settings/config/bindings/__init__.py
- terminal will pick bash/cmd based on os
- panel toggle is `ctrl` + `grave` (`)
=> Linux compatibility fixes by @cid0rz

biscuit/core/components/git/__init__.py
- Added Exception handling for importing Git.
=> Update __init__.py [Git]

biscuit/app.py, biscuit/core/components/floating/findreplace/__init__.py, biscuit/core/components/floating/notifications/__init__.py, biscuit/core/utils/binder.py
=> 72 notifications are rendered above system modals

biscuit/app.py, biscuit/core/components/floating/notifications/__init__.py, biscuit/core/components/floating/palette/__init__.py, biscuit/core/layout/__init__.py, biscuit/core/layout/menubar/__init__.py, biscuit/core/layout/menubar/item.py, biscuit/core/utils/events.py
=> 74 navigating menus causes main window to lose focus

biscuit/core/components/editors/texteditor/text.py
- Fixed the auto pair completion for quotes
=> fixed auto pair completion bug for quotes

biscuit/app.py, biscuit/core/api/__init__.py, biscuit/core/api/editors.py, biscuit/core/api/theme.py, biscuit/core/api/utils.py, biscuit/core/api/views.py, biscuit/core/components/games/__init__.py, biscuit/core/components/views/panel/terminal/__init__.py, biscuit/core/components/views/panel/terminal/shells/__init__.py, biscuit/core/components/views/panel/terminal/shells/default.py, biscuit/core/components/views/panel/terminal/shells/powershell.py, biscuit/core/components/views/panel/terminal/terminal.py, biscuit/core/components/views/panel/terminal/terminals/__init__.py, biscuit/core/components/views/sidebar/extensions/extension.py
- powershell
- editors, views API endpoints
=> Powershell for terminals

biscuit/core/utils/events.py
=> Cross platform support for window maximizing

biscuit/__init__.py, biscuit/core/__init__.py, biscuit/core/components/editors/texteditor/text.py, biscuit/core/components/extensions/__init__.py, biscuit/core/components/floating/notifications/__init__.py, biscuit/core/components/views/sidebar/extensions/extension.py, biscuit/core/components/views/sidebar/extensions/results.py, pyproject.toml, tests/test_version.py
new fields added for extensions list view
- author info
- short description
=> Better extensions GUI

README.md
Adding an "Issues" section to your README in a project's repository can provide valuable information to both contributors and users of your project. Here's why you might consider adding this section:
Issues Section:
- Transparency: It demonstrates that you welcome feedback and bug reports from users and contributors.
- Organization: It provides a central place for users and contributors to report and track issues, making it easier to manage and prioritize them.
- Instructions: You can include guidelines on how to report issues effectively, which can help streamline the issue submission process.
If you accept, put the hacktoberfest-accepted tag, please.
=> [DOCS] add issues section on README.md

biscuit/core/components/editors/texteditor/highlighter.py, biscuit/core/components/floating/palette/__init__.py, biscuit/core/layout/statusbar/__init__.py, biscuit/core/layout/statusbar/utils/button.py
- change the language mode of active editor from statubar
=> Change language mode from statusbar

biscuit/core/__init__.py, biscuit/core/components/floating/notifications/__init__.py, biscuit/core/components/floating/notifications/notification.py, biscuit/core/components/utils/toplevel.py, biscuit/core/settings/config/theme/theme.py, biscuit/extensions/dev.py
- Now multiple notifications are shown in stack
- They can be closed individually without closing all notifications
=> Notification stacks (multiple notifications)

biscuit/core/components/editors/texteditor/text.py, biscuit/core/components/utils/text.py, biscuit/core/layout/base/content/panel/__init__.py, biscuit/core/layout/base/sidebar/__init__.py, biscuit/core/layout/menubar/__init__.py, biscuit/core/utils/events.py
=> Add selection, view menus and callbacks

.github/workflows/code_quality.yml
=> Add Code Quality Analysis

biscuit/core/components/editors/texteditor/text.py
This would override the original definition, redefining anything can lead to confusion, I think these redefinitions were added by mistake
=> Function or method is being redefined

biscuit/core/components/views/sidebar/search/__init__.py, biscuit/core/components/views/sidebar/search/results.py
_original pr: #144 by @nfoert_
_issue: #130_
=> Re: Making the global search functional (#144)

biscuit/core/components/editors/__init__.py, biscuit/core/components/editors/markdown/__init__.py, biscuit/core/components/editors/markdown/renderer.py, biscuit/core/components/editors/texteditor/__init__.py, biscuit/core/settings/styles.py, requirements.txt
Fixes #136 
- markdown rendering in split pane 
- support for various markdown features
=> Markdown Editor

biscuit/core/__init__.py, biscuit/core/components/editors/__init__.py, biscuit/core/components/editors/breadcrumbs/__init__.py, biscuit/core/components/editors/breadcrumbs/pathview.py, biscuit/core/components/editors/texteditor/__init__.py, biscuit/core/components/editors/texteditor/highlighter.py, biscuit/core/components/editors/texteditor/linenumbers/__init__.py, biscuit/core/components/editors/texteditor/minimap.py, biscuit/core/components/editors/texteditor/text.py, biscuit/core/components/floating/__init__.py, biscuit/core/components/floating/definitions/__init__.py, biscuit/core/components/floating/definitions/item.py, biscuit/core/components/floating/findreplace/__init__.py, biscuit/core/components/lsp/client.py, biscuit/core/components/lsp/data.py, biscuit/core/components/lsp/handler.py, biscuit/core/components/utils/tree.py, biscuit/core/components/views/sidebar/search/results.py, biscuit/core/layout/base/content/editors/__init__.py, biscuit/core/layout/base/content/editors/tabs.py, biscuit/core/layout/statusbar/__init__.py, biscuit/core/settings/config/theme/theme.py
Fix #187
- goto-definition feature for LSP
- show multiple results of definition
- direct jump for single definitions
=> LSP goto definition 

LICENSE.md
=> update copyright year

biscuit/core/components/floating/autocomplete/kind.py, biscuit/core/components/floating/autocomplete/kinds.py, biscuit/core/components/utils/icon.py
=> Colors for completion items 

.gitignore, biscuit/__init__.py, biscuit/core/__init__.py, biscuit/core/components/__init__.py, biscuit/core/components/editors/image.py, biscuit/core/components/floating/palette/__init__.py, biscuit/core/components/floating/palette/actionset.py, biscuit/core/components/floating/palette/item.py, biscuit/core/components/floating/palette/searchbar.py, biscuit/core/components/history.py, biscuit/core/components/lsp/handler.py, biscuit/core/components/lsp/utils.py, biscuit/core/components/utils/__init__.py, biscuit/core/components/utils/fixedstack.py, biscuit/core/config.py, biscuit/core/events.py, biscuit/core/gui.py, biscuit/core/layout/base/content/editors/tab.py, biscuit/core/layout/menubar/__init__.py, biscuit/core/settings/config/theme/theme.py, biscuit/core/utils/events.py, pyproject.toml
=> File & Folder History Implementation

biscuit/core/components/editors/misc/welcome.py, biscuit/core/components/utils/__init__.py, biscuit/core/components/utils/linklabel.py, biscuit/core/settings/config/theme/theme.py
=> feat: add recent folders to welcome

biscuit/core/components/editors/texteditor/text.py, biscuit/core/layout/__init__.py
fix #232 
- implemented bracket pair colorization
- red highlights for unmatched brackets
- fixed border colors of root layout
=> feat: Bracket pair colorization 

biscuit/core/components/editors/texteditor/text.py, biscuit/core/components/floating/palette/__init__.py, biscuit/core/components/floating/palette/actionset.py, biscuit/core/components/floating/palette/searchbar.py, biscuit/core/components/lsp/__init__.py, biscuit/core/components/lsp/data.py, biscuit/core/components/lsp/handler.py, biscuit/core/components/views/sidebar/explorer/directorytree.py, biscuit/core/components/views/sidebar/explorer/menu.py, biscuit/core/components/views/sidebar/explorer/placeholder.py, biscuit/core/components/views/sidebar/outline/tree.py, biscuit/core/components/views/sidebar/sourcecontrol/placeholder.py, biscuit/core/layout/base/content/editors/editorsbar.py, biscuit/core/layout/base/content/editors/tabs.py, biscuit/core/layout/base/sidebar/slots.py, biscuit/core/layout/menubar/__init__.py, biscuit/core/layout/statusbar/__init__.py, biscuit/core/settings/__init__.py, biscuit/core/settings/config/bindings/__init__.py, biscuit/core/utils/binder.py, biscuit/core/utils/events.py
fixes #240 
- added symbols palette
- bindings of `ctrl+shift+k`
- go-to location implemented for outline view & symbols palette
=> Symbols Palette (`@` palette)

biscuit/core/components/editors/texteditor/text.py, biscuit/core/components/views/sidebar/explorer/directorytree.py, biscuit/core/components/views/sidebar/explorer/menu.py, biscuit/core/layout/base/content/editors/__init__.py, biscuit/core/layout/base/content/editors/tabs.py
=> feat: Reopen editor (explorer context menu)

biscuit/core/components/utils/__init__.py, biscuit/core/components/utils/closelistitem.py, biscuit/core/components/views/sidebar/explorer/__init__.py, biscuit/core/components/views/sidebar/explorer/open_editors.py, biscuit/core/components/views/sidebar/sidebarview.py, biscuit/core/layout/base/content/editors/__init__.py, biscuit/core/layout/base/content/editors/tabs.py
=> Open editors List

biscuit/core/components/editors/markdown/__init__.py
=> Markdown preview can be toggled

biscuit/core/components/editors/editor.py, biscuit/core/components/editors/texteditor/__init__.py, biscuit/core/components/views/panel/__init__.py, biscuit/core/components/views/panel/terminal/__init__.py, biscuit/core/components/views/panel/terminal/terminal.py, biscuit/core/config.py, biscuit/core/events.py, biscuit/core/exec.py, biscuit/core/gui.py, biscuit/core/layout/base/content/panel/__init__.py
fix #258 
Running files, compiler/interpreters for each language can be configured
=> Running files

biscuit/__init__.py, biscuit/core/components/floating/menu/__init__.py, biscuit/core/components/floating/menu/checkable.py, biscuit/core/components/utils/iconlabelbutton.py, biscuit/core/components/views/sidebar/explorer/__init__.py, biscuit/core/components/views/sidebar/sourcecontrol/__init__.py, biscuit/core/components/views/sidebar/sourcecontrol/git.py, biscuit/core/components/views/sidebar/sourcecontrol/placeholder.py, biscuit/core/layout/menubar/__init__.py, pyproject.toml
=> feat: Checkable menu items

biscuit/core/api/__init__.py, biscuit/core/components/editors/languages.py, biscuit/core/components/editors/texteditor/text.py
=> feat: Commenting and Uncommenting

biscuit/__init__.py, biscuit/core/components/editors/image.py, pyproject.toml
=> feat: Add zooming controls to image viewer

docs/docs/developer-docs/editing-wide-vs-feature-wide.md
Corrected grammatical errors to make reading and understanding easier
=> fixed spelling mistakes

poetry.lock, pyproject.toml, src/__init__.py, src/biscuit/common/minclosestdict.py, src/biscuit/common/textindex.py, src/biscuit/editor/__init__.py, src/biscuit/editor/diagnostic.py, src/biscuit/editor/hover/hover.py, src/biscuit/editor/text/text.py, src/biscuit/gui.py, src/biscuit/language/data.py, src/biscuit/language/handler.py, src/biscuit/views/logs/logs.py
=> feat: Added lsp diagnostics support (warning, error, info, hint)

extensions/dev.py, pyproject.toml, src/biscuit/__init__.py, src/biscuit/api/assistant.py, src/biscuit/api/base.py, src/biscuit/common/__init__.py, src/biscuit/common/chat/__init__.py, src/biscuit/common/chat/gemini.py, src/biscuit/common/chat/model.py, src/biscuit/common/menu/__init__.py, src/biscuit/common/menu/dropdown.py, src/biscuit/common/menu/menu.py, src/biscuit/views/ai/ai.py, src/biscuit/views/ai/chat.py
Added support for multiple Generative AI models
=> Genai models support

README.md, pyproject.toml, src/biscuit/__init__.py, src/biscuit/common/chat/gemini.py, src/biscuit/extensions/extension.py, src/biscuit/extensions/extensions.py, src/biscuit/views/ai/ai.py, src/biscuit/views/ai/chat.py, src/biscuit/views/terminal/ai.py, src/biscuit/views/terminal/terminalbase.py
Added support for using multiple models to generate terminal commands
=> Support for using multiple models to generate terminal commands

pyproject.toml, src/biscuit/__init__.py, src/biscuit/commands.py, src/biscuit/common/__init__.py, src/biscuit/common/menu/command.py, src/biscuit/common/menu/menu.py, src/biscuit/common/menu/submenu.py, src/biscuit/common/text_editor_menu.py, src/biscuit/editor/text/text.py, src/biscuit/gui.py, src/biscuit/layout/menubar/menubar.py
=> Text editor Context Menu

src/biscuit/commands.py, src/biscuit/config.py, src/biscuit/editor/text/linenumbers.py, src/biscuit/editor/text/text.py, src/biscuit/layout/menubar/menubar.py
added relative line numbering, addressing issue #417 
Uses existing solution and interacts with the toggle button in the edit menu.
=> Adding relative line numbering

src/biscuit/views/extensions/extensions.py, src/biscuit/views/extensions/results.py
fix #414
Added a filter icon and filter logic
=> Installed extensions filter for the extension center

.editorconfig, poetry.lock, pyproject.toml, src/biscuit/binder.py, src/biscuit/config.py, src/biscuit/editor/hover/renderer.py, src/biscuit/editor/text/text.py, src/biscuit/events.py
fix #319
- loads editorconfig files from parent directories after recursive lookup
=> feat: Added editorconfig support 

pyproject.toml, src/biscuit/__init__.py, src/biscuit/app.py, src/biscuit/extensions/__init__.py, src/biscuit/extensions/extensions.py, src/biscuit/extensions/viewer/__init__.py, src/biscuit/extensions/viewer/viewer.py, src/biscuit/gui.py, src/biscuit/views/extensions/results.py
fix #329 
- implements extension details pane
=> Extension details pane

src/biscuit/editor/editor.py, src/biscuit/editor/image.py, src/biscuit/layout/editors/editorsbar.py, src/biscuit/layout/editors/manager.py, src/biscuit/layout/editors/tab.py
=> fix: Update Breadcrumbs on editor switch/editor close

src/biscuit/common/fixedstack.py
Fixes #374
Fixes #375 
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/tomlin7/biscuit/issues/374?shareId=3617d255-e18f-4034-8f21-0ccd95fb0d63).
=> Recent folders/files: Bump newly opened to top if exists in db

pyproject.toml, src/biscuit/__init__.py, src/biscuit/cli/cli.py, src/biscuit/cli/extensions.py, src/biscuit/editor/text/text.py, src/biscuit/extensions/__init__.py, src/biscuit/extensions/manager.py, src/biscuit/extensions/scaffolder.py, src/biscuit/extensions/viewer/viewer.py, src/biscuit/views/extensions/extension.py
- `biscuit ext new <name>` (interactive)
- `biscuit ext dev`
- `biscuit ext test`
=> Extension dev
