CHANGELOG.md
biscuit/app.py
biscuit/core/components/editors/texteditor/__init__.py
biscuit/core/components/editors/texteditor/highlighter.py
biscuit/core/components/editors/texteditor/text.py
biscuit/core/layout/statusbar/__init__.py

fix #71 
---
- BOM (if exists) is used to decide the encoding of file
- BOM is not written as plain text to the text editor

Decide encoding of files with BOM (If exists)

---

biscuit/app.py
biscuit/config/settings.toml
biscuit/core/components/editors/breadcrumbs/pathview.py
biscuit/core/components/editors/misc/welcome.py
biscuit/core/components/editors/texteditor/autocomplete/item.py
biscuit/core/components/floating/menu/separator.py
biscuit/core/components/floating/notifications/__init__.py
biscuit/core/components/games/gameoflife.py
biscuit/core/components/utils/bubble.py
biscuit/core/components/utils/button.py
biscuit/core/components/utils/buttonsentry.py
biscuit/core/components/utils/entry.py
biscuit/core/components/utils/icon.py
biscuit/core/components/utils/iconbutton.py
biscuit/core/components/utils/iconlabelbutton.py
biscuit/core/components/utils/shortcut.py
biscuit/core/components/utils/toplevel.py
biscuit/core/components/views/sidebar/itembar.py
biscuit/core/components/views/sidebar/sidebarview.py
biscuit/core/layout/base/content/editors/__init__.py
biscuit/core/layout/base/sidebar/item.py
biscuit/core/layout/base/sidebar/slot.py
biscuit/core/layout/base/sidebar/slots.py
biscuit/core/layout/statusbar/utils/button.py
biscuit/core/settings/config/theme/theme.py
biscuit/core/settings/styles.py
biscuit/core/utils/events.py

Scale components based on screen dpi

---

biscuit/core/layout/statusbar/__init__.py
biscuit/core/layout/statusbar/utils/clock.py

- clock can now also use 12 hour format
- use palette to pick the formats

feat: Add 12/24 hour option for statusbar clock

---

biscuit/core/components/floating/palette/actionset.py
biscuit/core/layout/base/content/editors/__init__.py
biscuit/core/layout/base/content/editors/editorsbar.py

- implemented the common editors menu
- added active editors actionset
- improved actionset docs
helpful notes in the issue

Implement common editors menu #149

---

biscuit/core/components/editors/editor.py
biscuit/core/components/editors/languages.py
biscuit/core/components/editors/texteditor/text.py
biscuit/core/components/games/game.py
biscuit/core/components/lsp/test.py
biscuit/core/components/utils/__init__.py
biscuit/core/components/utils/button.py
biscuit/core/components/utils/canvas.py
biscuit/core/components/utils/frame.py
biscuit/core/components/utils/icon.py
biscuit/core/components/utils/iconbutton.py
biscuit/core/components/utils/label.py
biscuit/core/components/utils/menubutton.py
biscuit/core/components/utils/text.py
biscuit/core/components/views/view.py
biscuit/core/layout/__init__.py
biscuit/core/layout/base/__init__.py
biscuit/core/layout/base/content/__init__.py
biscuit/core/layout/base/content/editors/__init__.py
biscuit/core/layout/base/content/panel/__init__.py
biscuit/core/layout/base/content/panel/tabs.py
biscuit/core/layout/base/sidebar/__init__.py
biscuit/core/settings/__init__.py
biscuit/core/settings/config/__init__.py
biscuit/core/settings/config/bindings/loader.py

If a docstring fits in a single line (72 characters according to PEP8), it is
recommended to have the quotes on the same line.

One-line docstring should fit on one line with quotes

---

biscuit/core/components/views/sidebar/search/__init__.py
biscuit/core/components/views/sidebar/search/results.py

Making the global search functional

---

biscuit/core/components/floating/autocomplete/__init__.py

The lsp_mode of autocomplete widget is not changed appropriately according to the completion requests, this has been fixed.

lsp_mode is not being changed appropriately

---

biscuit/core/components/editors/texteditor/text.py
biscuit/core/components/floating/__init__.py
biscuit/core/components/floating/hover/__init__.py
biscuit/core/components/floating/palette/searchbar.py
biscuit/core/components/floating/rename.py
biscuit/core/components/lsp/__init__.py
biscuit/core/components/lsp/client.py
biscuit/core/components/lsp/data.py
biscuit/core/components/lsp/handler.py
biscuit/core/components/lsp/utils.py
biscuit/core/events.py
biscuit/core/gui.py

LSP Rename symbol

---

biscuit/__main__.py
biscuit/core/api/__init__.py
biscuit/core/components/editors/editor.py
biscuit/core/components/editors/texteditor/__init__.py
biscuit/core/components/editors/texteditor/menu.py
biscuit/core/components/floating/menu/__init__.py
biscuit/core/components/floating/palette/__init__.py
biscuit/core/components/floating/palette/searchbar.py
biscuit/core/components/views/sidebar/explorer/directorytree.py
biscuit/core/events.py
biscuit/core/exec.py
biscuit/core/gui.py
biscuit/core/layout/base/content/editors/__init__.py
biscuit/core/utils/events.py

Customizing run command for each editor

---

biscuit/core/components/editors/texteditor/text.py
biscuit/core/components/utils/iconlabelbutton.py
biscuit/core/config.py
biscuit/core/layout/menubar/__init__.py
biscuit/core/utils/events.py

Add block cursor (toggleable)

---

biscuit/core/components/editors/texteditor/text.py
biscuit/core/components/floating/palette/__init__.py
biscuit/core/components/floating/palette/searchbar.py
biscuit/core/components/lsp/__init__.py
biscuit/core/components/lsp/client.py
biscuit/core/layout/menubar/__init__.py
biscuit/core/utils/events.py

feat: Add editor specific commands to go menu

---

biscuit/core/commands.py
biscuit/core/components/editors/texteditor/__init__.py
biscuit/core/components/editors/texteditor/text.py
biscuit/core/gui.py
biscuit/core/layout/base/content/editors/__init__.py
biscuit/core/layout/base/content/editors/tab.py
biscuit/core/layout/base/content/editors/tabs.py

fix #280
In your [comment](https://github.com/billyeatcookies/biscuit/issues/280#issuecomment-2051108903), you also mentioned the idea of making a whole app destroy event. I have not implemented it in here, but i guess when the whole app is closed/destroyed, we can get the list of active editors and then just manually close them? I guess closing them will trigger the [close_tab()](https://github.com/vyshnav-vinod/biscuit/blob/3c6bf3df728f3dcbd1e390198730f51987c2fe0c/biscuit/core/layout/base/content/editors/tabs.py#L36) function of the tabs and it should trigger the save dialog??

feat: Ask user to save the file before they close the tab #280

---

biscuit/core/commands.py
biscuit/core/gui.py

The commit 30a251c has made the biscuit window to not close when 'x' is clicked. This is probably due to the "WM_DELETE_WINDOW" protocol only calling the [on_close_app](https://github.com/tomlin7/biscuit/blob/83437bd90fc4003d4a09ba47cb9445fe34f7f9c7/biscuit/core/gui.py#L64) function, which does not `destroy()` the tkinter window.
I checked the previous commit c9dd044 and this does close the window, so i guess the addition of the "WM_DELETE_WINDOW" protocol might have introduced the bug

fix: Window now closes when 'x' is clicked

---

biscuit/core/components/views/sidebar/github/issues.py

> Note: GitHub's REST API considers every pull request an issue, but not every issue is a pull request. For this reason, "Issues" endpoints may return both issues and pull requests in the response.
In the API [docs](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-repository-issues), it shows that the PRs also get included in the issues. So biscuit was also showing PRs with the issues. This PR should fix that.

fix: Fix PRs being displayed with issues

---

pyproject.toml
src/__init__.py
src/biscuit/common/actionset.py
src/biscuit/layout/drawer/drawer.py
src/biscuit/layout/panel/panelbar.py
src/biscuit/views/ai/ai.py
src/biscuit/views/debug/callstack.py
src/biscuit/views/debug/debug.py
src/biscuit/views/debug/variables.py
src/biscuit/views/drawer_item.py
src/biscuit/views/explorer/directorytree.py
src/biscuit/views/explorer/explorer.py
src/biscuit/views/explorer/open_editors.py
src/biscuit/views/extensions/results.py
src/biscuit/views/github/github.py
src/biscuit/views/github/issues.py
src/biscuit/views/github/prs.py
src/biscuit/views/logs/logs.py
src/biscuit/views/outline/outline.py
src/biscuit/views/problems/problems.py
src/biscuit/views/search/search.py
src/biscuit/views/sourcecontrol/changes.py
src/biscuit/views/sourcecontrol/stagedchanges.py
src/biscuit/views/terminal/ai.py
src/biscuit/views/terminal/terminal.py
src/biscuit/views/terminal/terminalbase.py
src/biscuit/views/toolbar.py

feat: Generate corrected terminal commands using assistant

---

pyproject.toml
src/__init__.py
src/biscuit/app.py
src/biscuit/common/helpers.py
src/biscuit/common/notifications/manager.py
src/biscuit/common/notifications/notification.py
src/biscuit/editor/text/editor.py
src/biscuit/git/git.py
src/biscuit/layout/statusbar/statusbar.py
src/biscuit/settings/theme/theme.py
src/biscuit/views/logs/logs.py
src/biscuit/views/terminal/terminal.py

Notification actions

---

src/biscuit/common/io.py
src/biscuit/common/notifications/manager.py
src/biscuit/language/handler.py

fix #364 
- send an empty configuration after initialization with `workspace/didChangeConfiguration`

fix: Fixed issues with basedpyright-langserver, Send empty configurations after server initialization

---

src/biscuit/common/menu/menu.py
src/biscuit/common/menu/submenu.py

fix #252 
Added support for submenus.

Submenus support for biscuit menus

---

CHANGELOG.md
pyproject.toml
src/biscuit/__init__.py
src/biscuit/binder.py
src/biscuit/commands.py
src/biscuit/layout/editors/editorsbar.py
src/biscuit/layout/editors/manager.py
src/biscuit/settings/bindings.py

I love the look of this code editor and wanted to contribute in my own small way. I arbitrarily set the cache maximum to ten so it doesn't start filling up profusely over long periods of development. If that's not necessary, I don't mind revising it at all!

feat: Restoring most recently closed tabs (#400)

---

src/biscuit/cli/cli.py

fix: #402 
Adds the path argument to the CLI so that `biscuit <path>` would start the editor and open said directory.

Adds path argument

---

src/biscuit/config.py
src/biscuit/events.py
src/biscuit/extensions/extensions.py
src/biscuit/views/extensions/extension.py

fix #427 
- store extensions in `~/.biscuit/extensions`s to 
- fallbacks to the executable basedir

Extensions userlevel

---

src/biscuit/extensions/extensions.py
src/biscuit/views/extensions/extensions.py
src/biscuit/views/extensions/results.py

Hi @tomlin7 ,
This closes Issue #409.
I've opted for a simple search logic that returns exact matches. Also searching for an empty string would give you the complete (initial) string as well.
Search feature can be triggered either by pressing the `SEARCH` icon in the top right (beside the `REFRESH` icon), or by pressing `<ENTER>` key after typing.

Extension Search bar implementation

---

src/biscuit/common/palette/palette.py
src/biscuit/common/palette/searchbar.py

feat: New command palette design

---

src/biscuit/common/palette/palette.py
src/biscuit/common/palette/searchbar.py

Command palette is now scrollable

feat: Make command palette scrollable, other UI improvements
